### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by HolyMiracle** [valKovbasiuk/selectors_test#1]
Привет!
По первому заданию все круто, никаких ошибок нету 👍 
По второму заданию есть единственное замечание по первому пункту задания:
Используя правило `a[href="about"]` ты выделишь только ссылки, типа `href="about"`, но не затронешь ссылки типа `href="https://.../about.html"`, поэтому в данной ситуации следует использовать такое правило: `a[href*="about"]`
Больше никаких ошибок не заметил :)

**Comment by valKovbasiuk** [comment]
у меня как раз были непонятки по этому пункту, поэтому я осознанно делал так.
спасибо

**Comment by HolyMiracle** [comment]
Рад, что помог :)
